apiVersion: v1
kind: Service
metadata:
  name: {{ include "meu-site.fullname" . }}-backend
  labels:
    {{- include "meu-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- with .Values.backend.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.portName }}
      protocol: TCP
      name: {{ .Values.backend.service.portName }}
  selector:
    {{- include "meu-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
