{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meu-site.fullname" . }}-database
  labels:
    {{- include "meu-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: {{ .Values.database.replicaCount | default 1 }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "meu-site.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meu-site.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: database
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          {{- if .Values.database.args }}
          args:
            {{- toYaml .Values.database.args | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.database.service.portName }}
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
          {{- if .Values.database.env }}
          env:
            {{- toYaml .Values.database.env | nindent 12 }}
          {{- end }}
          {{- if .Values.database.envFrom }}
          envFrom:
            {{- toYaml .Values.database.envFrom | nindent 12 }}
          {{- end }}
          {{- if and .Values.database.persistence.enabled (ne .Values.database.persistence.type "emptyDir") }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.database.persistence.mountPath }}
          {{- end }}
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.database.persistence.enabled }}
      volumes:
        - name: storage
          {{- if eq .Values.database.persistence.type "emptyDir" }}
          emptyDir: {}
          {{- else if eq .Values.database.persistence.type "hostPath" }}
          hostPath:
            path: {{ .Values.database.persistence.hostPath }}
            type: DirectoryOrCreate
          {{- else if eq .Values.database.persistence.type "pvc" }}
          persistentVolumeClaim:
            {{- if .Values.database.persistence.existingClaim }}
            claimName: {{ .Values.database.persistence.existingClaim }}
            {{- else }}
            claimName: {{ .Values.database.persistence.pvcName | default (printf "%s-db-pvc" (include "meu-site.fullname" .)) }}
            {{- end }}
          {{- end }}
      {{- end }}
{{- end }}
